### ISSUE TITLE
其他常见的树中 

### ISSUE THREAD

**Issue by YQYOnTheRoad** [LRH1993/android_interview#13]
树的带权路径长度

定义：树的带权路径长度规定为所有叶子结点的带权路径长度之和 

文章的例子的 “”树的WPL= 1*100 + 2*80 + 3**20 + 3**10 = 100 + 160 + 60 + 30 = 350。”

他的叶子节点不是 100 50 20 10 吗  80是弄错了吧？

**Comment by skylarliuu** [comment]
我也觉得应该是弄错了。应该是1*100+2*50+3*20+3*10 = 290

**Comment by skylarliuu** [comment]
我也觉得应该是弄错了

**Comment by LRH1993** [comment]
感谢指正，确实错了，已经纠正。
