### ISSUE TITLE
HashMap尾插还是头插？

### ISSUE THREAD

**Issue by j7672226** [LRH1993/android_interview#15]
![image](https://user-images.githubusercontent.com/23333288/33250780-9b750c4a-d36d-11e7-97da-ff5f8955ad21.png)
**在HashMap这一块，你的是尾插，而我测试的是头插，**
![image](https://user-images.githubusercontent.com/23333288/33250823-e531f67c-d36d-11e7-9dc1-9d643dca8e4c.png)

**Comment by LRH1993** [comment]
不明白头插和尾插是什么意思？ hashmap是根据hash散列的，没有没有固定顺序

**Comment by j7672226** [comment]
就是当hashmap经计算index值为一样时，就是你的数学：2、化学：8的index皆为10 的时候，后加入的化学不应该在头部，数学在next位置吗？
而我的化学和语文，index皆为13，化学为后加入的，我的化学在头部，语文在next位置。

**Comment by LRH1993** [comment]
应该是JDK版本不一样，我在1.8版本上看是尾部插入新元素
