### ISSUE TITLE
请问下面句话怎么理解？是不是存在歧义？

### ISSUE THREAD

**Issue by Merpyzf** [LRH1993/android_interview#2]
" 队列的头部是在队列中存放时间最长的元素，队列的尾部是保存在队列中存放时间最短的元素  " 这句话是不是存在歧义？

**Comment by LRH1993** [comment]
这句话是在哪篇文章中的？

**Comment by Merpyzf** [comment]
java集合框架中的Queue的介绍里的

**Comment by LRH1993** [comment]
队列先进先出，从队尾插入，队头取出。所以队头存在时间最长。可能与常规理解的有出入。改成从队头插入，队尾取出，队头时间最短，队尾时间最长，是不是更好理解一些？

**Comment by Merpyzf** [comment]
如果队列只插入元素而不取出元素的话，可以说队头元素在队列中保存的时间最长，因为是最先插入却又一直没被取出。 
"队列的尾部是保存在队列中存放时间最短的元素"对于这句话我的理解是:既然队列是按照顺序依次从队头取出的，那么尾部存放的元素也是在队头元素取出后，依次向前移，但仍保存在队列中，怎么能称之为队尾时间最短呢？

**Comment by LRH1993** [comment]
同一时间下，一个队列中，队头已经存在队列中的时间为最长，队尾已经存在队列中的时间也最短。
