### ISSUE TITLE
内容纠错

### ISSUE THREAD

**Issue by coderwjq** [LRH1993/android_interview#5]
3.1.1 Activity全方位解析
    2.特殊情况下的生命周期
    ①横竖屏切换
    ...并且把Activity销毁时onSaveInstanceState方法所保存的Bundle对象参数同时传递给onSaveInstanceState和onCreate方法...

是不是应该改为
    ...并且把Activity销毁时onSaveInstanceState方法所保存的Bundle对象参数同时传递给onRestoreInstanceState和onCreate方法...

**Comment by LRH1993** [comment]
对的，谢谢提醒，已修改
