### ISSUE TITLE
DoubleLink

### ISSUE THREAD

**Issue by EdwinSmartBoy** [LRH1993/android_interview#6]
您好,非常感谢您在百忙之中能够抽出时间提交了这么好的文章,非常感谢.在我查看数据结构---线性表这篇文章的时候,发现您使用java实现双链表的逻辑中,发现了逻辑问题,如下是insert方法中后半部分的代码逻辑: 
DNode<T> inode = getNode(index); 
//新插入的点  前驱为iNode的前驱  后继为inode
DNode<T> tnode = new DNode<T>(t, inode.prev, inode); 
//修改inode前驱的后继
inode.prev.next = tnode;
//此句代码应该是修改inode的前驱 应为 inode.prev = tnode 而源码中是如下所示
inode.next = tnode; 
mCount++;
return ;

//还望作者知悉,及时修改,再次感谢您在百忙之中能带来这么好的文章.

**Comment by LRH1993** [comment]
谢谢指正，看的很认真😋
