### ISSUE TITLE
用命令导出PDF报错

### ISSUE THREAD

**Issue by senlinxuefeng** [LRH1993/android_interview#8]
warn: "options" property is deprecated, use config.get(key) instead
(node:17917) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
error: error while generating page "java/basis/Collections-Framework.md":

Error: getaddrinfo ENOTFOUND upload-images.jianshu.io upload-images.jianshu.io:80
➜  android_interview-master git:(master)

**Comment by LRH1993** [comment]
这个不太清楚。可能是最近VPN不太稳定，建议多试几次。
