### ISSUE TITLE
LruCache错误

### ISSUE THREAD

**Issue by zhongjuncoder** [LRH1993/android_interview#9]
get的时候应该是把元素移到队尾，队头的才是最少使用的元素，所以当内存满的时候是把队头的元素删除。（//迭代器获取第一个对象，即队尾的元素，近期最少访问的元素。 Map.Entry<K, V> toEvict = map.entrySet().iterator().next();）这个获取到的是队头元素来的。

**Comment by LRH1993** [comment]
没找到太好的图片，就按照上面的图片描述，颠倒了队尾和队头。
